title: Bryan Li
email: bryanxli00@gmail.com
description: >- 
  Software Engineer
url: "https://bryxli.github.io"
github_username:  bryxli
remote_theme: tedivm/jekyll-theme-portfolio
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji