title: Bryan Li
email: bryanzero765@gmail.com
description: >- 
  Software Engineer
url: "https://bryxli.github.io"
homepage: "https://bryxli.github.io"
github_username: bryxli
linkedin_username: bryxli
remote_theme: tedivm/jekyll-theme-portfolio
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji
